//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amoba
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public int Id { get; set; }
        public string player1 { get; set; }
        public string player2 { get; set; }
        public string winner { get; set; }
        public System.DateTime date { get; set; }
    }
}
